version: "3"
# 最后编辑时间：2025-09-25

services:
  tailscale-drep:
    # 镜像地址
    image: ghcr.io/skyhhjmk/ip_derper_plus:v1.0.2
    # 容器名字
    container_name: taildrep
    # 主机名
    hostname: taildrep
    environment:
      # DREP地址，默认端口号443
      - DERP_ADDR=:443
      # 默认HTTP访问地址
      - DERP_HTTP_PORT=80
      # DREP服务器的互联网地址
      - DERP_HOST=X.X.X.X
      # DREP服务器CERTS存储路径
      # 部署后可以用ls -lah /var/lib/derper/和ls -lah /app/certs/查看相应目录下是否存在与互联网IP地址一致的.crt文件
      - DERP_CERTS=/app/certs/
      # 是否启用STUN穿透
      - DERP_STUN=true
      # STUN默认端口，注意端口配置时这里应该是UDP端口
      - DERP_STUN_PORT=3478
      # DREP服务器是否确认客户端，默认是不确认，所有客户端均可连接
      - DERP_VERIFY_CLIENTS=false
      # 在tailscale的console上添加的linux sever脚本
      - REG_BASH=sudo tailscale up --auth-key=tskey-auth-XXXXXXXXXXXXXX
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "3478:3478/udp"
    restart: always

